
export const FOOTER_COLLEGES = {
  mbbs: [
    { country: "Russia", code: "RU", names: ["Kazan Federal University", "Bashkir State Medical University", "Orenburg State Medical University", "Crimea Federal University", "First Moscow State Medical University"] },
    { country: "Georgia", code: "GE", names: ["Tbilisi State Medical University", "Batumi Shota Rustaveli State University", "David Tvildiani Medical University", "European University Georgia"] },
    { country: "Kazakhstan", code: "KZ", names: ["Al-Farabi Kazakh National University", "Kazakh National Medical University", "Astana Medical University", "South Kazakhstan Medical Academy"] },
    { country: "Kyrgyzstan", code: "KG", names: ["Osh State University", "Jalal-Abad State University", "International School of Medicine", "Asian Medical Institute"] },
    { country: "Uzbekistan", code: "UZ", names: ["Tashkent Medical Academy", "Samarkand State Medical University", "Bukhara State Medical Institute"] },
    { country: "China", code: "CN", names: ["Nanjing Medical University", "Jilin University", "China Medical University", "Dalian Medical University"] },
    { country: "Nepal", code: "NP", names: ["Tribhuvan University Institute of Medicine", "Kathmandu University School of Medical Sciences", "B.P. Koirala Institute of Health Sciences"] },
    { country: "Bangladesh", code: "BD", names: ["Dhaka National Medical College", "Bangladesh Medical College", "Jahurul Islam Medical College"] },
    { country: "Philippines", code: "PH", names: ["University of Santo Tomas", "AMA School of Medicine", "Our Lady of Fatima University"] },
    { country: "Poland", code: "PL", names: ["Medical University of Warsaw", "Jagiellonian University Medical College", "Medical University of Gdansk"] },
    { country: "Romania", code: "RO", names: ["Carol Davila University of Medicine and Pharmacy", "Iuliu Hatieganu University of Medicine and Pharmacy"] },
    { country: "Vietnam", code: "VN", names: ["Hanoi Medical University", "Ho Chi Minh City University of Medicine and Pharmacy"] },
    { country: "Serbia", code: "RS", names: ["University of Belgrade", "University of Novi Sad"] },
    { country: "Bulgaria", code: "BG", names: ["Medical University Sofia", "Medical University Plovdiv", "Medical University Varna"] },
  ],
  study: [
    { country: "Ireland", code: "IE", names: ["Trinity College Dublin", "University College Dublin", "National University of Ireland Galway"] },
    { country: "USA", code: "US", names: ["Harvard University", "Stanford University", "MIT", "University of California, Berkeley"] },
    { country: "UK", code: "GB", names: ["University of Oxford", "University of Cambridge", "Imperial College London", "UCL"] },
    { country: "Australia", code: "AU", names: ["University of Melbourne", "University of Sydney", "Australian National University"] },
    { country: "New Zealand", code: "NZ", names: ["University of Auckland", "University of Otago", "Victoria University of Wellington"] },
    { country: "Canada", code: "CA", names: ["University of Toronto", "McGill University", "University of British Columbia"] },
    { country: "Germany", code: "DE", names: ["Technical University of Munich", "Ludwig Maximilian University of Munich", "Heidelberg University"] },
    { country: "Italy", code: "IT", names: ["University of Bologna", "Sapienza University of Rome", "University of Milan"] },
    { country: "UAE", code: "AE", names: ["United Arab Emirates University", "Khalifa University", "American University of Sharjah"] },
    { country: "France", code: "FR", names: ["Sorbonne University", "École Polytechnique", "PSL Research University"] },
    { country: "Malta", code: "MT", names: ["University of Malta", "American University of Malta"] },
    { country: "Netherlands", code: "NL", names: ["University of Amsterdam", "Delft University of Technology", "Utrecht University"] },
    { country: "Denmark", code: "DK", names: ["University of Copenhagen", "Technical University of Denmark", "Aarhus University"] },
    { country: "Switzerland", code: "CH", names: ["ETH Zurich", "EPFL", "University of Zurich"] },
  ],
  india: [
    { state: "Uttar Pradesh", names: ["KGMU Lucknow", "IMS BHU", "AMU Aligarh"] },
    { state: "Haryana", names: ["Pt. B.D. Sharma PGIMS", "Kalpana Chawla Government Medical College"] },
    { state: "Rajasthan", names: ["SMS Medical College", "AIIMS Jodhpur", "SP Medical College"] },
    { state: "Maharashtra", names: ["KEM Hospital", "Grant Medical College", "AFMC Pune"] },
    { state: "Karnataka", names: ["Bangalore Medical College", "St. John's Medical College", "Kasturba Medical College"] },
    { state: "Madhya Pradesh", names: ["MGM Medical College", "Gandhi Medical College", "AIIMS Bhopal"] },
    { state: "Bihar", names: ["PMCH Patna", "AIIMS Patna", "IGIMS Patna"] },
    { state: "Uttarakhand", names: ["AIIMS Rishikesh", "Government Medical College Haldwani"] },
    { state: "Himachal Pradesh", names: ["IGMC Shimla", "Dr. RPGMC Tanda"] },
    { state: "Delhi", names: ["AIIMS New Delhi", "MAMC New Delhi", "VMMC New Delhi"] },
    { state: "Jharkhand", names: ["RIMS Ranchi", "MGM Medical College Jamshedpur"] },
  ]
};
